### ISSUE TITLE
Capturing sparta version number (and *more* of sparta's metadata)

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#67]
I've just been looking at "metadata_0.2.csv" and code for "extractMetadata()". Two observations:
1) The "2021_Ellcur" models should have the version number somewhere but these don't show up on the metadata sheet.
2) Since sparta v0.2.11 there is a simpler storage mechanism:
`out$sparta_version <- packages["sparta"]`

**Comment by drnickisaac** [comment]
Ah - it looks like someone changed the way sparta metadata is stored. Ahem - it was me.... So I think the solution is to have a cascade of three places to look for the version number, something like:
```
if(!is.null(out$sparta_version)) 
  meta_tmp$sparta_v <- out$sparta_version
else if(!is.null(attr(out, "metadata")$analysis$session_info))
  meta_tmp$sparta_v <- attr(out, "metadata")$analysis$session_info[[2]]["sparta"])
else if(!is.null(attr(out, "metadata")$analysis$session.info))
  meta_tmp$sparta_v <- attr(out, "metadata")$analysis$session.info$otherPkgs$sparta$Version
```
There may be a more elegant way to do this using `slice`.

**Comment by drnickisaac** [comment]
Whilst fixing this, please also extract the `provenance` field.

**Comment by 03rcooke** [comment]
Has this been done @FrancescaMancini @Kattur? Does the current metadata function extract provenance and sparta version number?

**Comment by Kattur** [comment]
@03rcooke , when I used the code written by @FrancescaMancini, to produce v.0.5 of the metadata, it certainly produced both a sparta version and provenance output for all those models run since 2021. The exception to this was for models run by Ellcur, for which only a sparta version was produced (i.e., the provenance wasn't picked up). I think that this may be because there is no provenance information in the provenance field of Ellcur files (instead it says 'Pairlist of length 0') ...

**Comment by 03rcooke** [comment]
Perfect, thanks @Kattur

**Comment by 03rcooke** [comment]
As far as I'm aware these requirements have now been implemented
